evolution:
  generations: 50
  steps: 200
  batch_size: 1
environment:
  width: 20
  height: 20
  num_resources: 20
  num_gathering_points: 1
network:
  substrate_input_dims:
    - 1
    - 2
  substrate_sheet_dims:
    - 1
    - 3
  substrate_output_dims:
    - 1
population:
  key: 0 # Key for population
  size: 150
  elitism: 2 # Number of members of pop to keep each generation
