evolution:
  generations: 50
  steps: 200
  batch_size: 1
environment:
  width: 20
  height: 20
  num_resources: 40
  num_gathering_points: 3
network:
  substrate_input_dims:
    - 3
    - 9
  substrate_sheet_dims:
    - 3
    - 3
  substrate_output_dims: 9
population:
  key: 0 # Key for population
  size: 100
  elitism: 20 # Number of members of pop to keep each generation
